export const ROLE_PERMISSIONS = {
  PLATFORM_ROLE_READ: 'platform.role.read',
  PLATFORM_ROLE_CREATE: 'platform.role.create',
  PLATFORM_ROLE_UPDATE: 'platform.role.update',
  PLATFORM_ROLE_DELETE: 'platform.role.delete',
  ROLE_READ: 'role.read',
  ROLE_UPDATE: 'role.update',
  ROLE_DELETE: 'role.delete',
  ROLE_PERMISSION_UPDATE: 'role.permission.update',
  COMPANY_ROLE_READ: 'company.role.read',
  COMPANY_ROLE_CREATE: 'company.role.create',
  COMPANY_ROLE_UPDATE: 'company.role.update',
  COMPANY_ROLE_DELETE: 'company.role.delete',
  PROJECT_ROLE_READ: 'project.role.read',
  PROJECT_ROLE_CREATE: 'project.role.create',
  PROJECT_ROLE_UPDATE: 'project.role.update',
  PROJECT_ROLE_DELETE: 'project.role.delete',
} as const;
