import { ProjectItem, ProjectType } from '@/src/types/projects';

export const PROJECT_TYPE_FILTERS: Array<ProjectType | 'All'> = [
  'All',
  'Manga',
  'Tooling',
  'Service',
];

export const PROJECTS: ProjectItem[] = [
  {
    id: 'dragon-blade',
    owner: 'Mangaka Studio',
    createdBy: 'user-haruto-sato',
    createdByName: 'Haruto Sato',
    createdAt: '2026-05-18T08:30:00.000Z',
    updatedAt: '2026-06-28T03:40:00.000Z',
    name: 'Dragon Blade',
    description:
      'Shonen manga project following a young sword bearer through arc, chapter, and page review.',
    type: 'Manga',
    editorBoard: 'Shonen Editorial Board',
    editorBoardLeaderName: 'Aiko Nakamura',
    editorBoardLeaderAvatarUri: 'https://i.pravatar.cc/160?img=47',
    editorBoardLeaderInitials: 'AN',
    currentUserRole: 'Lead Editor',
    activeMembers: 6,
    stars: 8,
    forks: 2,
    url: 'dragon-blade.mangaka.app',
    branch: 'chapter-12',
    rootFolders: 4,
    files: 42,
    materials: 18,
    applications: {
      pending: 2,
      approved: 1,
      rejected: 1,
      cancelled: 0,
    },
    tasks: {
      pending: 2,
      inProgress: 3,
      review: 2,
      done: 1,
    },
    contributors: 6,
    stats: {
      pagesReviewed: 126,
      frameComments: 34,
      completionRate: 68,
      lastUpdated: 'Updated 2h ago',
    },
    language: 'Manga',
    languageColor: '#F59E0B',
    avatarInitials: 'DB',
    avatarBg: '#7C3AED',
    coverUri: 'https://picsum.photos/seed/mangaka-dragon-blade/900/620',
  },
  {
    id: 'moonlight-ronin',
    owner: 'Mangaka Studio',
    createdBy: 'user-yumi-tanaka',
    createdByName: 'Yumi Tanaka',
    createdAt: '2026-04-26T10:15:00.000Z',
    updatedAt: '2026-06-27T09:10:00.000Z',
    name: 'Moonlight Ronin',
    description:
      'Seinen review workspace for a wandering ronin story with night combat and cinematic pacing.',
    type: 'Manga',
    editorBoard: 'Seinen Editorial Board',
    editorBoardLeaderName: 'Kenji Mori',
    editorBoardLeaderAvatarUri: 'https://i.pravatar.cc/160?img=12',
    editorBoardLeaderInitials: 'KM',
    currentUserRole: 'Reviewer',
    activeMembers: 5,
    stars: 5,
    forks: 1,
    url: 'moonlight-ronin.mangaka.app',
    branch: 'chapter-08',
    rootFolders: 3,
    files: 31,
    materials: 14,
    applications: {
      pending: 1,
      approved: 2,
      rejected: 0,
      cancelled: 0,
    },
    tasks: {
      pending: 1,
      inProgress: 2,
      review: 1,
      done: 1,
    },
    contributors: 5,
    stats: {
      pagesReviewed: 88,
      frameComments: 21,
      completionRate: 54,
      lastUpdated: 'Updated yesterday',
    },
    language: 'Manga',
    languageColor: '#38BDF8',
    avatarInitials: 'MR',
    avatarBg: '#0F766E',
    coverUri: 'https://picsum.photos/seed/mangaka-moonlight-ronin/900/620',
  },
  {
    id: 'frame-cleaner',
    owner: 'Editorial Tools',
    createdBy: 'user-minh-phan',
    createdByName: 'Minh Phan',
    createdAt: '2026-05-29T02:20:00.000Z',
    updatedAt: '2026-06-28T01:05:00.000Z',
    name: 'Frame Cleaner',
    description:
      'Internal tooling project for reviewing frames, cleanup notes, and production-ready panels.',
    type: 'Tooling',
    editorBoard: 'Production Tools',
    editorBoardLeaderName: 'Minh Phan',
    editorBoardLeaderAvatarUri: 'https://i.pravatar.cc/160?img=33',
    editorBoardLeaderInitials: 'MP',
    currentUserRole: 'Maintainer',
    activeMembers: 3,
    stars: 2,
    forks: 0,
    url: 'frame-cleaner.tools.mangaka.app',
    branch: 'main',
    rootFolders: 2,
    files: 12,
    materials: 6,
    applications: {
      pending: 1,
      approved: 1,
      rejected: 0,
      cancelled: 0,
    },
    tasks: {
      pending: 0,
      inProgress: 1,
      review: 1,
      done: 1,
    },
    contributors: 3,
    stats: {
      pagesReviewed: 42,
      frameComments: 11,
      completionRate: 72,
      lastUpdated: 'Updated 3h ago',
    },
    language: 'TypeScript',
    languageColor: '#3178C6',
    avatarInitials: 'FC',
    avatarBg: '#334155',
    coverUri: 'https://picsum.photos/seed/mangaka-frame-cleaner/900/620',
  },
  {
    id: 'lettering-queue',
    owner: 'Production Ops',
    createdBy: 'user-aya-mori',
    createdByName: 'Aya Mori',
    createdAt: '2026-06-03T07:45:00.000Z',
    updatedAt: '2026-06-28T04:35:00.000Z',
    name: 'Lettering Queue',
    description:
      'Production service for coordinating lettering passes, page readiness, and release handoff.',
    type: 'Service',
    editorBoard: 'Production Ops',
    editorBoardLeaderName: 'Aya Mori',
    editorBoardLeaderAvatarUri: 'https://i.pravatar.cc/160?img=25',
    editorBoardLeaderInitials: 'AM',
    currentUserRole: 'Coordinator',
    activeMembers: 4,
    stars: 3,
    forks: 1,
    url: 'lettering-queue.ops.mangaka.app',
    branch: 'production',
    rootFolders: 3,
    files: 20,
    materials: 9,
    applications: {
      pending: 3,
      approved: 2,
      rejected: 0,
      cancelled: 0,
    },
    tasks: {
      pending: 2,
      inProgress: 2,
      review: 2,
      done: 1,
    },
    contributors: 4,
    stats: {
      pagesReviewed: 75,
      frameComments: 18,
      completionRate: 61,
      lastUpdated: 'Updated 45m ago',
    },
    language: 'React Native',
    languageColor: '#61DAFB',
    avatarInitials: 'LQ',
    avatarBg: '#BE123C',
    coverUri: 'https://picsum.photos/seed/mangaka-lettering-queue/900/620',
  },
  {
    id: 'night-market',
    owner: 'Mangaka Studio',
    createdBy: 'user-linh-tran',
    createdByName: 'Linh Tran',
    createdAt: '2026-06-14T11:00:00.000Z',
    updatedAt: '2026-06-24T13:20:00.000Z',
    name: 'Night Market',
    description:
      'Pilot manga workspace for an arc set inside a hidden market of spirits and coded lanterns.',
    type: 'Manga',
    editorBoard: 'Pilot Board',
    editorBoardLeaderName: 'Linh Tran',
    editorBoardLeaderAvatarUri: 'https://i.pravatar.cc/160?img=5',
    editorBoardLeaderInitials: 'LT',
    currentUserRole: 'Artist',
    activeMembers: 2,
    stars: 1,
    forks: 0,
    url: 'night-market.mangaka.app',
    branch: 'pilot',
    rootFolders: 2,
    files: 9,
    materials: 7,
    applications: {
      pending: 1,
      approved: 0,
      rejected: 0,
      cancelled: 0,
    },
    tasks: {
      pending: 1,
      inProgress: 1,
      review: 0,
      done: 0,
    },
    contributors: 2,
    stats: {
      pagesReviewed: 19,
      frameComments: 5,
      completionRate: 28,
      lastUpdated: 'Updated 4d ago',
    },
    language: 'Manga',
    languageColor: '#A3E635',
    avatarInitials: 'NM',
    avatarBg: '#92400E',
    coverUri: 'https://picsum.photos/seed/mangaka-night-market/900/620',
  },
];
