import { ProjectItem, ProjectType } from '@/src/types/projects';

export const PROJECT_TYPE_FILTERS: Array<ProjectType | 'All'> = [
  'All',
  'Manga',
  'Tooling',
  'Service',
];

export const PROJECTS: ProjectItem[] = [
  {
    id: 'dragon-blade',
    owner: 'Mangaka Studio',
    name: 'Dragon Blade',
    type: 'Manga',
    editorBoard: 'Shonen Editorial Board',
    currentUserRole: 'Lead Editor',
    activeMembers: 6,
    stars: 8,
    forks: 2,
    url: 'dragon-blade.mangaka.app',
    branch: 'chapter-12',
    rootFolders: 4,
    files: 42,
    materials: 18,
    applications: {
      pending: 2,
      approved: 1,
      rejected: 1,
      cancelled: 0,
    },
    tasks: {
      pending: 2,
      inProgress: 3,
      review: 2,
      done: 1,
    },
    contributors: 6,
    stats: {
      pagesReviewed: 126,
      frameComments: 34,
      completionRate: 68,
      lastUpdated: 'Updated 2h ago',
    },
    language: 'Manga',
    languageColor: '#F59E0B',
    avatarInitials: 'DB',
    avatarBg: '#7C3AED',
  },
  {
    id: 'moonlight-ronin',
    owner: 'Mangaka Studio',
    name: 'Moonlight Ronin',
    type: 'Manga',
    editorBoard: 'Seinen Editorial Board',
    currentUserRole: 'Reviewer',
    activeMembers: 5,
    stars: 5,
    forks: 1,
    url: 'moonlight-ronin.mangaka.app',
    branch: 'chapter-08',
    rootFolders: 3,
    files: 31,
    materials: 14,
    applications: {
      pending: 1,
      approved: 2,
      rejected: 0,
      cancelled: 0,
    },
    tasks: {
      pending: 1,
      inProgress: 2,
      review: 1,
      done: 1,
    },
    contributors: 5,
    stats: {
      pagesReviewed: 88,
      frameComments: 21,
      completionRate: 54,
      lastUpdated: 'Updated yesterday',
    },
    language: 'Manga',
    languageColor: '#38BDF8',
    avatarInitials: 'MR',
    avatarBg: '#0F766E',
  },
  {
    id: 'frame-cleaner',
    owner: 'Editorial Tools',
    name: 'Frame Cleaner',
    type: 'Tooling',
    editorBoard: 'Production Tools',
    currentUserRole: 'Maintainer',
    activeMembers: 3,
    stars: 2,
    forks: 0,
    url: 'frame-cleaner.tools.mangaka.app',
    branch: 'main',
    rootFolders: 2,
    files: 12,
    materials: 6,
    applications: {
      pending: 1,
      approved: 1,
      rejected: 0,
      cancelled: 0,
    },
    tasks: {
      pending: 0,
      inProgress: 1,
      review: 1,
      done: 1,
    },
    contributors: 3,
    stats: {
      pagesReviewed: 42,
      frameComments: 11,
      completionRate: 72,
      lastUpdated: 'Updated 3h ago',
    },
    language: 'TypeScript',
    languageColor: '#3178C6',
    avatarInitials: 'FC',
    avatarBg: '#334155',
  },
  {
    id: 'lettering-queue',
    owner: 'Production Ops',
    name: 'Lettering Queue',
    type: 'Service',
    editorBoard: 'Production Ops',
    currentUserRole: 'Coordinator',
    activeMembers: 4,
    stars: 3,
    forks: 1,
    url: 'lettering-queue.ops.mangaka.app',
    branch: 'production',
    rootFolders: 3,
    files: 20,
    materials: 9,
    applications: {
      pending: 3,
      approved: 2,
      rejected: 0,
      cancelled: 0,
    },
    tasks: {
      pending: 2,
      inProgress: 2,
      review: 2,
      done: 1,
    },
    contributors: 4,
    stats: {
      pagesReviewed: 75,
      frameComments: 18,
      completionRate: 61,
      lastUpdated: 'Updated 45m ago',
    },
    language: 'React Native',
    languageColor: '#61DAFB',
    avatarInitials: 'LQ',
    avatarBg: '#BE123C',
  },
  {
    id: 'night-market',
    owner: 'Mangaka Studio',
    name: 'Night Market',
    type: 'Manga',
    editorBoard: 'Pilot Board',
    currentUserRole: 'Artist',
    activeMembers: 2,
    stars: 1,
    forks: 0,
    url: 'night-market.mangaka.app',
    branch: 'pilot',
    rootFolders: 2,
    files: 9,
    materials: 7,
    applications: {
      pending: 1,
      approved: 0,
      rejected: 0,
      cancelled: 0,
    },
    tasks: {
      pending: 1,
      inProgress: 1,
      review: 0,
      done: 0,
    },
    contributors: 2,
    stats: {
      pagesReviewed: 19,
      frameComments: 5,
      completionRate: 28,
      lastUpdated: 'Updated 4d ago',
    },
    language: 'Manga',
    languageColor: '#A3E635',
    avatarInitials: 'NM',
    avatarBg: '#92400E',
  },
];
