export const ERROR = {
  CFLEMAIL: 'Email is exist.',
  EVLLOGIN: 'Invalid email or password.',
  EVLCURRENTPASSWORD: 'Current password is incorrect.',
  EVLACTIVE: 'Please verify your email before login.',
  EVLVERIFYEMAIL: 'Invalid, expired, or already used verify email token.',
  EVLSAMEPASSWORD: 'New password cannot be the same as the old password.',
  EVLRESETPASSWORD: 'Invalid or expired reset password token.',
  SVLOGIN: 'Server is not available to login.',
  SVLOGOUT: 'Server is not available to logout.',
  SVREGISTER: 'Server is not available to register.',
  SVSYSDEFAULTROLE: 'System default role is not configured.',
  SVENV: 'Can not get environment variable.',
  EXPTOKEN: 'Token is expired',
  NFFOLDER: 'Folder is not exist',
  NFFILE: 'File is not exist',
  NFTASK: 'Task is not exist',
  NFFRAME: 'Frame is not exist',
  NFCOMMENT: 'Comment is not exist',
  NFPERMISSION: 'Permission is not exist',
  NFROLE: 'Role is not exist',
  CFROLECODE: 'Role code already exists',
  CFLROLEASSIGNED: 'Role is assigned to users or projects',
  NFPROJECT: 'Project is not exist',
  NFBOARD: 'Editor board is not exist',
  NFCOMPANY: 'Company is not exist',
  NFUSER: 'User is not exist',
  NFMATERIAL: 'Material is not exist',
  NFAPPLICATION: 'Application is not exist',
  NFDEFAULTPRJROLE: 'Default project role is not exist',
  EVLROLEASSIGNED: 'Role is assigned to users or projects and cannot be deleted.',
  EVLPERMISSIONSCOPE: 'Permission scope does not match role scope.',
  SVPERMISSION: 'Server is not available to get user permissions.',
  SVCREPROJECT: 'Server is not available to create project.',
  SVGETPROJECTS: 'Server is not available to get projects.',
  SVGETPROJECT: 'Server is not available to get project.',
  SVUPDATEPROJECT: 'Server is not available to update project.',
  SVDELETEPROJECT: 'Server is not available to delete project.',
  SVADDPROJECTMEMBER: 'Server is not available to add member to project.',
  SVGETPROJECTMEMBERS: 'Server is not available to get project members.',
  SVGETPROJECTMEMBER: 'Server is not available to get project member.',
  SVUPDATEPROJECTMEMBER: 'Server is not available to update project member.',
  SVREMOVEPROJECTMEMBER: 'Server is not available to remove member from project.',
  SVGETPROJECTBOARD: 'Server is not available to get project editor board.',
  SVUPDATEPROJECTBOARD: 'Server is not available to update project editor board.',
  SVGETPROJECTAPPLICATIONS: 'Server is not available to get project applications.',
  SVCREPROJECTAPPLICATION: 'Server is not available to create project application.',
  SVGETAPPLICATION: 'Server is not available to get application.',
  SVUPDATEAPPLICATION: 'Server is not available to update application.',
  SVDELETEAPPLICATION: 'Server is not available to delete application.',
  SVGETPROJECTFOLDERS: 'Server is not available to get project folders.',
  SVCREPROJECTFOLDER: 'Server is not available to create project folder.',
  EVLRMPRJOWNER: 'Owner can not be removed from project.',
  EVLPRJROLE: 'Invalid project role.',
  EVLPRJFOLDER: 'Folder does not belong to project.',
  SVCREBOARD: 'Server is not available to create editor board.',
  SVGETBOARDS: 'Server is not available to get editor boards.',
  SVGETBOARD: 'Server is not available to get editor board.',
  SVUPDATEBOARD: 'Server is not available to update editor board.',
  SVDELETEBOARD: 'Server is not available to delete editor board.',
  SVADDBOARDMEMBER: 'Server is not available to add member to editor board.',
  SVGETBOARDMEMBERS: 'Server is not available to get editor board members.',
  SVGETBOARDMEMBER: 'Server is not available to get editor board member.',
  SVREMOVEBOARDMEMBER: 'Server is not available to remove member from editor board.',
  EVLRMOWNER: 'Owner can not be removed from board.',
  SVUPDBOARDMEMBER: 'Server is not available to update editor board member.',
  SVGETBOARDPROJECTS: 'Server is not available to get editor board projects.',
  SVADDBOARDPROJECTS: 'Server is not available to add projects to editor board.',
  CFLBOARDPROJECTS: 'Some projects are already assigned to another board.',
  SVGETBOARDAPPLICATIONS: 'Server is not available to get editor board applications.',
  SVGETFOLDER: 'Server is not available to get folder.',
  SVUPDATEFOLDER: 'Server is not available to update folder.',
  SVDELETEFOLDER: 'Server is not available to delete folder.',
  SVGETFOLDERFILES: 'Server is not available to get folder files.',
  SVCREATEFILE: 'Server is not available to create file.',
  SVGETFOLDERCHILDREN: 'Server is not available to get folder children.',
  SVCREATECHILDFOLDER: 'Server is not available to create child folder.',
  SVGETFILE: 'Server is not available to get file.',
  SVUPDATEFILE: 'Server is not available to update file.',
  SVDELETEFILE: 'Server is not available to delete file.',
  SVGETFILEMATERIALS: 'Server is not available to get file materials.',
  SVCREATEMATERIAL: 'Server is not available to create material.',
  SVGETFILETASKS: 'Server is not available to get file tasks.',
  SVCREATETASK: 'Server is not available to create task.',
  SVGETMATERIAL: 'Server is not available to get material.',
  SVUPDATEMATERIAL: 'Server is not available to update material.',
  SVDELETEMATERIAL: 'Server is not available to delete material.',
  SVGETTASK: 'Server is not available to get task.',
  SVUPDATETASK: 'Server is not available to update task.',
  SVDELETETASK: 'Server is not available to delete task.',
  SVGETTASKCHILDREN: 'Server is not available to get task children.',
  SVGETTASKFRAMES: 'Server is not available to get task frames.',
  SVCREATEFRAME: 'Server is not available to create frame.',
  SVGETTASKCOMMENTS: 'Server is not available to get task comments.',
  SVGETFRAME: 'Server is not available to get frame.',
  SVUPDATEFRAME: 'Server is not available to update frame.',
  SVDELETEFRAME: 'Server is not available to delete frame.',
  SVGETFRAMECOMMENTS: 'Server is not available to get frame comments.',
  SVCREATECOMMENT: 'Server is not available to create comment.',
  SVGETPROJECTSTAT: 'Server is not available to get project stat.',
  SVUPDATEPROJECTSTAT: 'Server is not available to update project stat.',
  SVDELETEPROJECTSTAT: 'Server is not available to delete project stat.',
  NFPROJECTSTAT: 'Project stat is not exist',
  SVGETPROJECTSTATSBYPROJECT: 'Server is not available to get project stats.',
  SVIMPORTPROJECTSTATS: 'Server is not available to import project stats.',
  EVLSYSROLES: 'Invalid system roles',
  EVLGOOGLELINKSTATE: 'Invalid Google link state',
  CFLGOOGLEACCOUNT: 'Google account is already linked',
  SVGETUSER: 'Server is not available to get user.',
  SVUPDATEUSER: 'Server is not available to update user.',
  SVGETUSERS: 'Server is not available to get users.',
  SVCREATEUSER: 'Server is not available to create user.',
  SVGETUSERROLES: 'Server is not available to get user roles.',
  SVADDUSERROLES: 'Server is not available to add user roles.',
  SVUPDATEUSERROLES: 'Server is not available to update user roles.',
  SVGETROLES: 'Server is not available to get roles.',
  SVGETROLE: 'Server is not available to get role.',
  SVDELETEROLE: 'Server is not available to delete role.',
  SVGETROLEPERMISSIONS: 'Server is not available to get role permissions.',
  SVUPDATEROLEPERMISSIONS: 'Server is not available to update role permissions.',
  SVGETPERMISSIONS: 'Server is not available to get permissions.',
  SVGETPERMISSION: 'Server is not available to get permission.',
  SVUPDATEPERMISSION: 'Server is not available to update permission.',
  SVLEAVEPROJECT: 'Server is not available to leave project.',
  SVLEAVEBOARD: 'Server is not available to leave board.',
  SVGETVOTES: 'Server is not available to get votes.',
  SVVOTE: 'Server is not available to cast vote.',
  EVLSUBTASKDEP: 'Cannot change subtask status: parent task must be completed first.',
  SVRESTOREMATERIAL: 'Server is not available to restore material.',
  EVLINTERNALAPPROVAL: 'Internal approval is required before submission to Editor Board.',
};
