export const ERROR = {
  CFLEMAIL: 'Email is exist.',
  EVLLOGIN: 'Invalid email or password.',
  EVLACTIVE: 'Please verify your email before login.',
  EVLVERIFYEMAIL: 'Invalid or expired verify email token.',
  EVLRESETPASSWORD: 'Invalid or expired reset password token.',
  SVLOGIN: 'Server is not available to login.',
  SVLOGOUT: 'Server is not available to logout.',
  SVREGISTER: 'Server is not available to register.',
  SVENV: 'Can not get environment variable.',
  EXPTOKEN: 'Token is expired',
  NFFOLDER: 'Folder is not exist',
  NFFILE: 'File is not exist',
  NFTASK: 'Task is not exist',
  NFFRAME: 'Frame is not exist',
  NFCOMMENT: 'Comment is not exist',
  NFROLE: 'Role is not exist',
  NFPROJECT: 'Project is not exist',
  NFCOMPANY: 'Company is not exist',
  NFUSER: 'User is not exist',
  NFMATERIAL: 'Material is not exist',
  SVPERMISSION: 'Server is not available to get user permissions.',
};
