export const ERROR = {
  CFLEMAIL: 'Email is exist.',
  EVLLOGIN: 'Invalid email or password.',
  EVLACTIVE: 'Please verify your email before login.',
  EVLVERIFYEMAIL: 'Invalid or expired verify email token.',
  EVLRESETPASSWORD: 'Invalid or expired reset password token.',
  SVLOGIN: 'Server is not available to login.',
  SVLOGOUT: 'Server is not available to logout.',
  SVREGISTER: 'Server is not available to register.',
  SVENV: 'Can not get environment variable.',
  EXPTOKEN: 'Token is expired',
  NFFOLDER: 'Folder is not exist',
  NFFILE: 'File is not exist',
  NFTASK: 'Task is not exist',
  NFFRAME: 'Frame is not exist',
  NFCOMMENT: 'Comment is not exist',
  NFROLE: 'Role is not exist',
  NFPROJECT: 'Project is not exist',
  NFBOARD: 'Editor board is not exist',
  NFCOMPANY: 'Company is not exist',
  NFUSER: 'User is not exist',
  NFMATERIAL: 'Material is not exist',
  SVPERMISSION: 'Server is not available to get user permissions.',
  SVCREBOARD: 'Server is not available to create editor board.',
  SVGETBOARDS: 'Server is not available to get editor boards.',
  SVGETBOARD: 'Server is not available to get editor board.',
  SVUPDATEBOARD: 'Server is not available to update editor board.',
  SVDELETEBOARD: 'Server is not available to delete editor board.',
  SVADDBOARDMEMBER: 'Server is not available to add member to editor board.',
  SVGETBOARDMEMBERS: 'Server is not available to get editor board members.',
  SVGETBOARDMEMBER: 'Server is not available to get editor board member.',
  SVREMOVEBOARDMEMBER: 'Server is not available to remove member from editor board.',
  EVLRMOWNER: 'Owner can not be removed from board.',
  SVUPDBOARDMEMBER: 'Server is not available to update editor board member.',
  SVGETBOARDPROJECTS: 'Server is not available to get editor board projects.',
  SVADDBOARDPROJECTS: 'Server is not available to add projects to editor board.',
  CFLBOARDPROJECTS: 'Some projects are already assigned to another board.',
  SVGETBOARDAPPLICATIONS: 'Server is not available to get editor board applications.',
};
